### ISSUE TITLE
Web app activated instead of android app

### ISSUE THREAD

**Issue by itshappeningbaby** [esm7/obsidian-geo-helper#1]
Hello there. Thanks for the app!

I am using android 14 on a Google pixel 7 pro.
Last version of Obsidian. 

Map View is “calling” the app in order to fetch the location but instead of the app, it takes me to the web version of it, on Chrome, that needs internet to work. 

I would like to embed my current location to my Daily Note even if I don't have internet connection. 

Thanks a lot!

![ezgif com-optimize](https://github.com/esm7/obsidian-geo-helper/assets/149935043/eb986d53-c5cc-4092-a81c-0152bd1552e2)

**Comment by esm7** [comment]
In the Map View settings under GPS, do you have Geo helper type set to "installed app"?

**Comment by itshappeningbaby** [comment]
Oh yes!  You are right I am sorry!!
